[velero] add kubernetes disaster recovery feature
dojot/ansible-dojot pull request #159
Opened 2022-01-10 11:50 UTC by ewerton-silva00

* **Please check if the PR fulfills these requirements**
  * [ ] Tests for the changes have been added (for bug fixes / features)
  * [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
We currently do not have a backup and restore solution for Kubernetes resources.

* **What is the new behavior (if this is a feature change)?**
From this feature we will have backup and restore from Dojot, as well as disaster recovery from the Kubernetes cluster.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#2227

* **Other information**:

2022-01-11 12:34 UTC, marianoleonardo requested changes
Deixei alguns comentários com sugestões e dúvidas!

2022-01-11 12:34 UTC, marianoleonardo commented on roles/velero/defaults/main.yml
> +---
As variáveis que estão sendo definidas aqui (`roles/velero/defaults/main.yml`) são as mesmas que estão sendo definidas em (`inventories/example_local/group_vars/all/velero.yaml`). Acredito que isso possa causar confusão, pois a meu entendimento, na hierarquia de variáveis do ansible, ele dará prioridade as variáveis que se encontram dentro de `defaults`.

2022-01-11 12:34 UTC, marianoleonardo commented on roles/velero/handlers/main.yml
> +---
Visto que o arquivo está vazio, acho que poderíamos excluí-lo.

2022-01-11 12:34 UTC, marianoleonardo commented on roles/velero/vars/main.yml
> +---
Acredito que essas variáveis poderiam estar definidas em `roles/velero/defaults/main.yml`

2022-01-11 12:34 UTC, marianoleonardo commented on roles/velero/tests/inventory
> +localhost
Esse arquivo de inventário está correto?

2022-01-11 12:34 UTC, marianoleonardo commented on roles/velero/tests/test.yml
> +---
Para que serviria esse arquivo? Entendo que ele tem uma funcionalidade que pode ser executada pelo playbook `velero.yaml` que está na raiz do projeto certo?

2022-01-11 13:27 UTC, ewerton-silva00 commented on roles/velero/defaults/main.yml
> +---
O ansible lê primeiro o `inventories/example_local/group_vars/all/velero.yaml`, pois são as variáveis definidas pelo usuário final.

As variáveis `roles/velero/defaults/main.yml` são lidas caso não exista a opção acima, pois são variáveis padrão definidas pelo mantenedor da role caso o usuário final não passe nada.

2022-01-11 13:29 UTC, ewerton-silva00 commented on roles/velero/tests/inventory
> +localhost
Sim. Esse inventário é utilizado pra execução de testes na role.

Essa estrutura é padrão, criada via `ansible-galaxy init role/velero`.

2022-01-11 13:30 UTC, ewerton-silva00 commented on roles/velero/handlers/main.yml
> +---
Essa estrutura é padrão, criada via `ansible-galaxy init role/velero`.

É uma boa práticar manter, mesmo que não tenha nada.

2022-01-11 13:34 UTC, ewerton-silva00 commented on roles/velero/tests/test.yml
> +---
O arquivo `velero.yaml` é o playbook utilizado para chamar a role `velero`. Exemplo:

```bash
ansible-playbook \
	--ask-pass \
	--ask-become-pass \
	--inventory inventories/example_local/hosts.yaml \
	--extra-vars "velero_kubeconfig_file_path=/home/ewerton/.kube/k3s.yaml" \
	--extra-vars "velero_binary_install=true" \
	--extra-vars "velero_storage_s3url=http://localhost:9000" \
	--extra-vars "velero_aws_access_key=AKIAIOSFODNN7TEST" \
	--extra-vars "velero_aws_secret_key=NS3GnYS1gjYe9kTbEnIGZzn2WSccF5RGjQlmYdld" \
	velero.yaml
```

Mesmo esquema utilizado para executar as demais roles que não são core da Dojot, como por exemplo, `nginx.yaml`, `haproxy.yaml`...

2022-01-11 13:44 UTC, ewerton-silva00 commented on roles/velero/defaults/main.yml
> +---
```
defaults/main.yml: These variables have the lowest priority of any variables available, and can be easily overridden by any other variable, including inventory variables.
```

2022-02-07 17:00 UTC, marianoleonardo approved these changes
Great Job!!!

2022-02-07 18:01 UTC, danielapetito approved these changes

2022-02-08 14:04 UTC, merged