[ansible] Deployment - Update HTTP Agent
dojot/ansible-dojot pull request #160
Opened 2022-01-17 14:26 UTC by danielapetito

[ansible] Deployment - Update HTTP Agent

2022-01-18 12:49 UTC, marianoleonardo requested changes
Dani, acredito que ficou faltando a variável `HTTP_AGENT_HTTPS_CA` com o valor `/certs/cabundle.crt` dentro do http-agent

2022-01-18 13:22 UTC, danielapetito commented
@marianoleonardo conforme conversamos, no Ansible/K8s só é configurado os certificados no http-agent-cert-sidecar.
Não temos configuração no http-agent

2022-01-18 19:30 UTC, ewerton-silva00 approved these changes
Ok!

2022-01-19 11:45 UTC, marianoleonardo approved these changes
Great Job!

2022-01-20 11:04 UTC, ewerton-silva00 approved these changes
Ok!

2022-01-20 14:08 UTC, marianoleonardo approved these changes

2022-01-20 14:36 UTC, merged