add metrics server k8s
dojot/ansible-dojot pull request #200
Opened 2022-06-24 13:11 UTC by rodrigoemereciano

* **Please check if the PR fulfills these requirements**
  * [ ] Tests for the changes have been added (for bug fixes / features)
  * [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature
* **What is the current behavior?** (You can also link to an open issue here)
The cluster k8s not have instaled metrics server 
* **What is the new behavior (if this is a feature change)?**
The k8s cluster will have the metrics server installed
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2022-06-24 13:39 UTC, gabrielifg submitted a review, later dismissed
GG!!!

2022-06-27 18:43 UTC, marianoleonardo requested changes

2022-06-27 23:48 UTC, rodrigoemereciano commented on roles/k8s-cluster/master-node/tasks/main.yaml
> +  command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
Excelente observação, alterei para a implementação via helm na versão 3.8.2 em um namespace separado.

2022-06-28 11:19 UTC, marianoleonardo approved these changes

2022-06-28 11:48 UTC, gabrielifg approved these changes
👏👏

2022-06-28 11:55 UTC, merged