Vault
dojot/ansible-dojot pull request #230
Opened 2022-11-17 11:45 UTC by danielapetito

* **Please check if the PR fulfills these requirements**
  * [ ] Tests for the changes have been added (for bug fixes / features)
  * [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
Deploy Hashicorp Vault and random secrets

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:
[DEVOPS-11 - ](https://jira.cpqd.com.br/browse/DEVOPS-11) [DOJOT] - HashiCorp Vault para secrets

2022-11-17 17:41 UTC, marianoleonardo requested changes
Deixei alguns comentários

2022-11-17 17:43 UTC, danielapetito commented on inventories/example_local/group_vars/all/labels.yaml
> +  - k3s-01
ajustado

2022-11-17 17:44 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.influxdb_password
ajustado

2022-11-17 17:45 UTC, danielapetito commented on roles/k3s-cluster/defaults/main.yml
> +k3s_release_version: 1.21.14
o consul precisa do kubernetes 1.21 por isso a mudança.
pensando nisso tenho q atualizar o k8s tmb e testar...  :-)

2022-11-17 17:46 UTC, danielapetito commented on roles/undeploy/dojot/tasks/main.yaml
> +    #- { file: '.cluster-keys.yaml' }
ajustado

2022-11-17 17:47 UTC, danielapetito commented on roles/vault/confs/tasks/main.yaml
> +#  debug: "If error occurs, it means that you already have this secrets. Please ignore."
ajustado

2022-11-17 17:50 UTC, danielapetito commented on volume.yaml
> +
na linha 27 à 32 é execução no dojot_nodes
na linha 121 à 125 é execução no master_nodes

precisa ter nos 2 locais..

2022-11-17 17:51 UTC, danielapetito commented on roles/vault/confs/tasks/main.yaml
> +#     msg: "If error occurs, it means that you already have this secrets. Please ignore."
ajustado

2022-11-17 17:52 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.kong_password
Ajustado

2022-11-17 17:52 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.mongodb_password
Ajustado

2022-11-17 18:34 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.devm_password
ajustado

2022-11-17 18:34 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.MINIO_SECRET_KEY
ajustado

2022-11-17 18:34 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.keycloak_password
ajustado

2022-11-17 18:34 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.backstage_secret
ajustado

2022-11-17 18:34 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.kafka_ws_secret
ajustado

2022-11-17 18:34 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.dojot_secret
ajustado

2022-11-17 18:35 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.x509_ejbca_password
ajustado

2022-11-17 18:35 UTC, danielapetito commented on roles/dojot-basic/tasks/main.yaml
> +  #local_action: command ls {{ playbook_dir }}/inventories/secrets/.MINIO_ACCESS_KEY
ajustado

2022-11-17 18:35 UTC, danielapetito commented on roles/databases/postgresql/templates/postgres_init_config_map.yaml.j2.old
> +        EOSQL
ajustado

2022-11-18 15:39 UTC, marianoleonardo approved these changes
Ótimo trabalho!! 👏🏼👏🏼👏🏼

2022-11-18 16:57 UTC, abeserrab approved these changes

2022-11-18 17:01 UTC, merged