deploy flowbroker and fix report_manager
dojot/ansible-dojot pull request #240
Opened 2022-12-20 19:56 UTC by danielapetito

* **Please check if the PR fulfills these requirements**
  * [ ] Tests for the changes have been added (for bug fixes / features)
  * [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2022-12-20 20:22 UTC, gabrielifg submitted a review, later dismissed
Bom trabalho!!!

2022-12-21 12:38 UTC, marianoleonardo requested changes
Deixei alguns comentários

2022-12-21 12:38 UTC, marianoleonardo commented on deploy.yaml
> +        - flowbroker
Acho que aqui poderia substituir por rabbitmq

2022-12-21 12:38 UTC, marianoleonardo commented on deploy.yaml
> +        - 100k
Essas duas tags devem ser removidas

2022-12-21 12:38 UTC, marianoleonardo commented on deploy.yaml
> +        - 100k
Essas duas tags devem ser removidas

2022-12-21 12:44 UTC, danielapetito commented on deploy.yaml
> +        - 100k
ok.. removido

2022-12-21 12:44 UTC, danielapetito commented on deploy.yaml
> +        - 100k
ok.. removido.

2022-12-21 12:44 UTC, danielapetito commented on deploy.yaml
> +        - flowbroker
ok.. adicionado.

2022-12-21 12:47 UTC, marianoleonardo approved these changes

2022-12-21 12:47 UTC, merged