Nginx deployment
dojot/ansible-dojot pull request #81
Opened 2020-11-24 14:16 UTC by LeonardoMariano

* **Please check if the PR fulfills these requirements**
  * [ ] Tests for the changes have been added (for bug fixes / features)
  * [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
We don't have a load balancer for dojot v0.4.4

* **What is the new behavior (if this is a feature change)?**
Nginx will be used as a load balancer

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
Yes, this PR is connected to dojot/dojot#1863 and dojot/dojot#1837

* **Other information**:

2020-11-24 15:02 UTC, andersonluisribeiro requested changes
Good job! I think the docs/vars.md file should be updated as well, as new variables have been added.

2020-11-24 19:58 UTC, eduardogmisiuk reviewed
Nice! I left only one comment.

2020-11-24 19:58 UTC, eduardogmisiuk commented on roles/nginx/defaults/main.yaml
> +nginx_version: '1.18*'
In the `docs/vars.md` you wrote that the default version is 1.19. Shouldn't it be too?

2020-11-26 18:14 UTC, eduardogmisiuk approved these changes
LGTM! But don't do a git push force!

2020-12-09 19:22 UTC, andersonluisribeiro approved these changes
:+1:

2020-12-10 13:16 UTC, mprevide approved these changes
It looks ok to me, but I don't know much about nginx, ansible and k8s.

2020-12-10 13:30 UTC, merged